package com.oathforge.toolkit.util;

import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.security.SecureRandom;
import java.security.spec.KeySpec;
import java.util.Base64;

import javax.crypto.Cipher;
import javax.crypto.SecretKey;
import javax.crypto.SecretKeyFactory;
import javax.crypto.spec.GCMParameterSpec;
import javax.crypto.spec.PBEKeySpec;
import javax.crypto.spec.SecretKeySpec;

import com.oathforge.toolkit.enums.ExceptionEnum;
import com.oathforge.toolkit.exception.ConflictException;
import com.oathforge.toolkit.exception.IllegalArgumentException;
import com.oathforge.toolkit.exception.InternalServerErrorException;

import lombok.experimental.UtilityClass;
import lombok.extern.slf4j.Slf4j;

@Slf4j
@UtilityClass
public class EncryptionUtil {

	private static final String ALGORITHM = "AES/GCM/NoPadding";
	private static final int TAG_LENGTH_BIT = 128;
	private static final int IV_SIZE = 12;

	/**
	 * Encrypts the provided plain-text value using AES/GCM and a key derived from
	 * the supplied base key.
	 * <p>
	 * The returned payload includes both the generated IV and the encrypted bytes,
	 * encoded together as a Base64 string so that the output can be safely stored
	 * or transported as text.
	 *
	 * @param data plain-text value to encrypt
	 * @param baseKey source key used to derive the runtime encryption key
	 * @return Base64 payload containing the IV followed by the encrypted bytes
	 * @throws Exception when the encryption process cannot be completed
	 */
	public String encrypt(String data, String baseKey) throws Exception {
		SecretKey key = deriveKey(baseKey);
		if (key == null) {
			throw new IllegalArgumentException(ExceptionEnum.UTL0001.name(), ExceptionEnum.UTL0001.getValue());
		}
		log.debug("Encrypting data...");
		Cipher cipher = Cipher.getInstance(ALGORITHM);
		byte[] iv = new byte[IV_SIZE];
		new SecureRandom().nextBytes(iv);
		GCMParameterSpec spec = new GCMParameterSpec(TAG_LENGTH_BIT, iv);
		cipher.init(Cipher.ENCRYPT_MODE, key, spec);
		byte[] encrypted = cipher.doFinal(data.getBytes(StandardCharsets.UTF_8));
		byte[] encryptedIVAndText = new byte[IV_SIZE + encrypted.length];
		System.arraycopy(iv, 0, encryptedIVAndText, 0, IV_SIZE);
		System.arraycopy(encrypted, 0, encryptedIVAndText, IV_SIZE, encrypted.length);
		log.debug("Data encrypted successfully.");
		return Base64.getEncoder().encodeToString(encryptedIVAndText);
	}

	/**
	 * Decrypts a Base64 payload previously produced by {@link #encrypt(String, String)}.
	 * <p>
	 * The method expects the input to contain both the IV and the encrypted bytes
	 * in the format generated by this utility.
	 *
	 * @param encryptedData Base64 payload containing IV and encrypted bytes
	 * @param baseKey source key used to derive the runtime decryption key
	 * @return decrypted plain-text value
	 * @throws Exception when the payload cannot be decrypted
	 */
	public String decrypt(String encryptedData, String baseKey) throws Exception {
		SecretKey key = deriveKey(baseKey);
		if (key == null) {
			throw new IllegalArgumentException(ExceptionEnum.UTL0001.name(), ExceptionEnum.UTL0001.getValue());
		}
		log.debug("Decrypting data...");
		byte[] decodedData = Base64.getDecoder().decode(encryptedData);
		byte[] iv = new byte[IV_SIZE];
		System.arraycopy(decodedData, 0, iv, 0, iv.length);
		GCMParameterSpec spec = new GCMParameterSpec(TAG_LENGTH_BIT, iv);
		Cipher cipher = Cipher.getInstance(ALGORITHM);
		cipher.init(Cipher.DECRYPT_MODE, key, spec);
		byte[] encrypted = new byte[decodedData.length - IV_SIZE];
		System.arraycopy(decodedData, IV_SIZE, encrypted, 0, encrypted.length);
		byte[] decrypted = cipher.doFinal(encrypted);
		log.debug("Data decrypted successfully.");
		return new String(decrypted, StandardCharsets.UTF_8);
	}

	private SecretKey deriveKey(String baseKey) {
		String deriveKey = "PBKDF2WithHmacSHA256";
		int keySize = 256;
		int iterationCount = 65536;
		byte[] salt = "static-salt-value".getBytes();

		try {
			SecretKeyFactory factory = SecretKeyFactory.getInstance(deriveKey);
			KeySpec spec = new PBEKeySpec(baseKey.toCharArray(), salt, iterationCount, keySize);
			byte[] secretKey = factory.generateSecret(spec).getEncoded();
			return new SecretKeySpec(secretKey, "AES");
		} catch (Exception e) {
			throw new InternalServerErrorException(ExceptionEnum.UTL0002.name(), ExceptionEnum.UTL0002.getValue());
		}
	}

	/**
	 * Generates a deterministic 8-digit string from a serial number and an
	 * 8-digit seed.
	 * <p>
	 * This method is useful when you need a short reproducible derived value that
	 * is not a direct exposure of the original serial number.
	 *
	 * @param serialNumber source serial number
	 * @param seed 8-digit seed used during the transformation
	 * @return 8-digit derived value
	 */
	public String applySerialHashAsString(long serialNumber, int seed) {
		validateSeed(seed);
		long xorResult = ((long) seed) ^ serialNumber;
		String hash = calculateSHA256(Long.toString(xorResult));
		String leftmost8 = hash.substring(0, 8);
		long parsed = Long.parseUnsignedLong(leftmost8, 16);
		long modResult = parsed % 100_000_000L;
		return String.format("%08d", modResult);
	}

	/**
	 * Calculates the SHA-256 hash of the provided input and returns it as a
	 * hexadecimal string.
	 *
	 * @param input input text
	 * @return hexadecimal SHA-256 hash
	 */
	public String calculateSHA256(String input) {
		try {
			MessageDigest digest = MessageDigest.getInstance("SHA-256");
			byte[] encodedhash = digest.digest(input.getBytes(StandardCharsets.UTF_8));
			return bytesToHex(encodedhash);
		} catch (NoSuchAlgorithmException e) {
			throw new ConflictException(ExceptionEnum.UTL0007.name(), ExceptionEnum.UTL0007.getValue());
		}
	}

	private String bytesToHex(byte[] hash) {
		StringBuilder hexString = new StringBuilder(2 * hash.length);
		for (byte b : hash) {
			String hex = Integer.toHexString(0xff & b);
			if (hex.length() == 1) {
				hexString.append('0');
			}
			hexString.append(hex);
		}
		return hexString.toString();
	}

	/**
	 * Validates that the provided seed is an 8-digit numeric value.
	 * <p>
	 * This method is intended to protect callers that rely on a fixed-width seed
	 * during deterministic transformations such as {@link #applySerialHashAsString(long, int)}.
	 *
	 * @param seed seed value to validate
	 */
	public void validateSeed(int seed) {
		if (seed < 10000000 || seed > 99999999) {
			throw new ConflictException(ExceptionEnum.UTL0008.name(), ExceptionEnum.UTL0008.getValue());
		}
	}
}
